
# cargo-vet config file

[cargo-vet]
version = "0.10"

[policy.dataport]
audit-as-crates-io = true

[[exemptions.dataport]]
version = "0.0.0"
criteria = "safe-to-deploy"

[[exemptions.doc-comment]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"
